apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- configmap.yaml
- ingress.yaml
- namespace.yaml
- secret.yaml
- service.yaml
- statefulset.yaml
- initdbconfig.yaml
images:
- name: IMAGE_BACKEND_PLACEHOLDER
  newName: laurihakala/dwk-project-backend
  newTag: 7c9a494180eda3aba49ddbb636eb90fcc3f18a46
- name: IMAGE_BROADCASTER_PLACEHOLDER
  newName: laurihakala/dwk-project-broadcaster
  newTag: 7c9a494180eda3aba49ddbb636eb90fcc3f18a46
- name: IMAGE_FRONTEND_PLACEHOLDER
  newName: laurihakala/dwk-project-frontend
  newTag: 7c9a494180eda3aba49ddbb636eb90fcc3f18a46
