apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- vanilla-manifests/deployment.yaml
- vanilla-manifests/configamp.yaml
- vanilla-manifests/ingress.yaml
- vanilla-manifests/namespace.yaml
- vanilla-manifests/secret.yaml
- vanilla-manifests/service.yaml
- vanilla-manifests/statefulset.yaml
- vanilla-manifests/initdbconfig.yaml
images:
- name: IMAGE_FRONTEND_PLACEHOLDER
  newName: laurihakala/dwk-project-frontend
  newTag: fdafd7088d04892815ed037cf30ca4f61c7af2f7
- name: IMAGE_BACKEND_PLACEHOLDER
  newName: laurihakala/dwk-project-backend
  newTag: fdafd7088d04892815ed037cf30ca4f61c7af2f7
- name: IMAGE_BROADCASTER_PLACEHOLDER
  newName: laurihakala/dwk-project-broadcaster
  newTag: fdafd7088d04892815ed037cf30ca4f61c7af2f7
