apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- configmap.yaml
- ingress.yaml
- namespace.yaml
- secret.yaml
- service.yaml
- statefulset.yaml
- initdbconfig.yaml
images:
- name: IMAGE_BACKEND_PLACEHOLDER
  newName: laurihakala/dwk-project-backend
  newTag: 69130dd964a85a12ee62f8ec95c0cbab4cee7a09
- name: IMAGE_BROADCASTER_PLACEHOLDER
  newName: laurihakala/dwk-project-broadcaster
  newTag: 69130dd964a85a12ee62f8ec95c0cbab4cee7a09
- name: IMAGE_FRONTEND_PLACEHOLDER
  newName: laurihakala/dwk-project-frontend
  newTag: 69130dd964a85a12ee62f8ec95c0cbab4cee7a09
