apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- vanilla-manifests/deployment.yaml
- vanilla-manifests/configamp.yaml
- vanilla-manifests/ingress.yaml
- vanilla-manifests/namespace.yaml
- vanilla-manifests/secret.yaml
- vanilla-manifests/service.yaml
- vanilla-manifests/statefulset.yaml
- vanilla-manifests/initdbconfig.yaml
images:
- name: IMAGE_BACKEND_PLACEHOLDER
  newName: laurihakala/dwk-project-backend
  newTag: f23c52c587992f08ef9d338462375fe3f2ff20ad
- name: IMAGE_BROADCASTER_PLACEHOLDER
  newName: laurihakala/dwk-project-broadcaster
  newTag: f23c52c587992f08ef9d338462375fe3f2ff20ad
- name: IMAGE_FRONTEND_PLACEHOLDER
  newName: laurihakala/dwk-project-frontend
  newTag: f23c52c587992f08ef9d338462375fe3f2ff20ad
