name: Release 4-gitops-app

on:
  push:
    branches:
      - main
    paths:
      - '4-gitops/app/**'
      - '4-gitops/app/vanilla-manifests/**'
      - '4-gitops/app/dwk-front/**'
      - '.github/workflows/gitops-app.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      
      # LOGIN TO DOCKER
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push back
    - name: Publish to Registry
      uses: docker/build-push-action@v1
      with:
        repository: laurihakala/dwk-project-backend
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ github.sha }}
        path: 4-gitops/app/dwk-back/

        # Build and push front
    - name: Publish to Registry
      uses: docker/build-push-action@v1
      with:
        repository: laurihakala/dwk-project-frontend
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ github.sha }}
        path: 4-gitops/app/dwk-front/

        # Build and push broadcaster
    - name: Publish to Registry
      uses: docker/build-push-action@v1
      with:
        repository: laurihakala/dwk-project-broadcaster
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ github.sha }}
        path: 4-gitops/app/dwk-broadcaster/

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Set up Kustomize
      working-directory: 4-gitops/vanilla-manifests/
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Update yamls
    - name: Update yamls
      working-directory: 4-gitops/vanilla-manifests/
      run: |-
        ./kustomize edit set image IMAGE_FRONTEND_PLACEHOLDER=laurihakala/dwk-project-frontend:${{ github.sha }}
        ./kustomize edit set image IMAGE_BACKEND_PLACEHOLDER=laurihakala/dwk-project-backend:${{ github.sha }}
        ./kustomize edit set image IMAGE_BROADCASTER_PLACEHOLDER=laurihakala/dwk-project-broadcaster:${{ github.sha }}

    # Commit and push
    - uses: EndBug/add-and-commit@v5
      with:
        add: '4-gitops/vanilla-manifests/kustomization.yaml'
        message: New version release for gitops-app ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
